### ISSUE TITLE
3D Scour

### ISSUE THREAD

**Issue by ramap1219** [SedFoam/sedfoam#50]
Hi

I have the following error when running 3D scour tutorial as it is...Any help would be much appreciated.

**Part: k
 Modifying field k of type volScalarField

 Putting "inletprofilek(pos().z)" into field k at t = "0" if condition "true" is true
 Keeping patches unaltered

--> FOAM FATAL IO ERROR:
Unknown patchField type kqRWallFunction for patch type wall

Valid patchField types are :

78
(
advective
calculated
codedFixedValue
codedMixed
cyclic
cyclicACMI
cyclicAMI
cyclicRepeatAMI
cyclicSlip
directionMixed
empty
externalCoupled
extrapolatedCalculated
fanPressure
fanPressureJump
fixedFluxExtrapolatedPressure
fixedFluxPressure
fixedGradient
fixedInternalValue
fixedJump
fixedJumpAMI
fixedMean
fixedMeanOutletInlet
fixedPressureCompressibleDensity
fixedProfile
fixedValue
freestream
freestreamPressure
groovyBC
groovyBCDirection
groovyBCFixedValue
groovyBCJump
groovyPartialSlip
groovyTotalPressure
inletOutlet
inletOutletTotalTemperature
interfaceCompression
mapped
mappedField
mappedFixedInternalValue
mappedFixedPushedInternalValue
mixed
nonuniformTransformCyclic
outletInlet
outletMappedUniformInlet
partialSlip
phaseHydrostaticPressure
plenumPressure
pressure
prghPressure
prghTotalHydrostaticPressure
prghTotalPressure
prghUniformDensityHydrostaticPressure
processor
processorCyclic
rotatingTotalPressure
sliced
slip
symmetry
symmetryPlane
syringePressure
timeVaryingMappedFixedValue
totalPressure
totalTemperature
turbulentInlet
turbulentIntensityKineticEnergyInlet
uniformDensityHydrostaticPressure
uniformFixedGradient
uniformFixedValue
uniformInletOutlet
uniformJump
uniformJumpAMI
uniformTotalPressure
variableHeightFlowRate
waveSurfacePressure
waveTransmissive
wedge
zeroGradient
)

file: /sediment/sedfoam/tutorials/3DTest/0/k.boundaryField.cylinder from line 26 to                                                                                                                                line 27.

    From function static Foam::tmp<Foam::fvPatchField<Type> > Foam::fvPatchField<Type>::New(const Foam::fvPatc                                                                                                                               h&, const Foam::DimensionedField<Type, Foam::volMesh>&, const Foam::dictionary&) [with Type = double]
    in file /trinity/shared/apps-cfd/openfoam/openFOAM-7/OpenFOAM-7/src/finiteVolume/lnInclude/fvPatchFieldNew                                                                                                                               .C at line 131.

FOAM exiting**

Thanks in advance

Rama

**Comment by CyrilleBonamy** [comment]
Thanks for creating an issue.
I fixed the problem here: https://github.com/SedFoam/sedfoam/blob/master/tutorials/3DScour/system/controlDict#L57

**Comment by ramap1219** [comment]
hi, many thanks...that worked..however, it seems to be crashing while doing the first iteration, shown in attached...any suggestion please?
![floatingPointError](https://user-images.githubusercontent.com/79201409/108751338-fccfe200-7539-11eb-994e-b83d4dbf1ae2.PNG)

**Comment by CyrilleBonamy** [comment]
maybe you can decrease the time step at the start of the simulation, and increase it afterwards?

**Comment by ramap1219** [comment]
hi, thanks for the advice..doesn't look like a timestep issue though as still seems to be failing even after reducing timestep to 1e-8...

Could you please confirm if it is working on your end?

Courant Number mean: 7.16285e-07 max: 8.46455e-06
Max Ur Courant Number = 1.75385e-07
Interface Courant Number mean: 7.16285e-07 max: 8.46455e-06
deltaT = **1.2e-08** < 0.0002
Time = 1.2e-08

**Comment by ramap1219** [comment]
Hi, sorry could you please confirm if 3D tutorial is working from your end ? I'm trying my best but couldn't get that working, just wants to know if I'm doing anything wrong..

Thanks

**Comment by CyrilleBonamy** [comment]
just to reproduce the problem : how many cores do you use?

**Comment by ramap1219** [comment]
thanks for the reply, we have an in-house cluster of about 280cores...so cores not a problem.

**Comment by CyrilleBonamy** [comment]
is it at the end of the first iteration? 

We are not using the openfoam version 7. So I will check if this relates to this ...

**Comment by ramap1219** [comment]
yes that's right. just at the end of the first iteration.

**Comment by CyrilleBonamy** [comment]
it's ok now

Keep me in touch

**Comment by wbw-wb** [comment]
Hello, I have been following your sedfoam since last year. Recently I encountered some problems when running your 3D case. I hope to get your help, thank you very much 

--> FOAM FATAL IO ERROR: 
Attempt to cast type patch to type lduInterface

file: /home/dyfluid/OpenFOAM/dyfluid-v1812/run/3DScour/0/Ua.boundaryField.lateral

    From function To& Foam::refCast(From&, const Foam::dictionary&) [with To = const Foam::lduInterface; From = const Foam::fvPatch]
    in file /home/dyfluid/OpenFOAM/OpenFOAM-v1812/src/OpenFOAM/lnInclude/typeInfo.H at line 158.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::IOerror::abort() at ??:?
#2  Foam::lduInterface const& Foam::refCast<Foam::lduInterface const, Foam::fvPatch const>(Foam::fvPatch const&, Foam::dictionary const&) at ??:?
#3  Foam::cyclicFvPatchField<Foam::Vector<double> >::cyclicFvPatchField(Foam::fvPatch const&, Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) at ??:?
#4  Foam::fvPatchField<Foam::Vector<double> >::adddictionaryConstructorToTable<Foam::cyclicFvPatchField<Foam::Vector<double> > >::New(Foam::fvPatch const&, Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) at ??:?
#5  Foam::fvPatchField<Foam::Vector<double> >::New(Foam::fvPatch const&, Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#6  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::Boundary::readField(Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#7  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::readFields(Foam::dictionary const&) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#8  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::readFields() in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#9  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::GeometricField(Foam::IOobject const&, Foam::fvMesh const&, bool) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#10  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#11  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#12  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#13  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
#14  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields

**Comment by wbw-wb** [comment]
Hello, I have been following your sedfoam since last year. Recently I encountered some problems when running your 3D case. I hope to get your help, thank you very much
swak4Foam: Allocating new repository for sampledMeshes
--> FOAM Warning : 
    From function groovyBCFvPatchField<Type>::groovyBCFvPatchField(const fvPatch& p,const DimensionedField<Type, volMesh>& iF,const dictionary& dict)
    in file groovyBCFvPatchField.C at line 136
    No value defined for Ua on inlet therefore using the internal field next to the patch


--> FOAM FATAL IO ERROR: 
Attempt to cast type patch to type lduInterface

file: /home/dyfluid/OpenFOAM/dyfluid-v1812/run/3DScour/0/Ua.boundaryField.lateral

    From function To& Foam::refCast(From&, const Foam::dictionary&) [with To = const Foam::lduInterface; From = const Foam::fvPatch]
    in file /home/dyfluid/OpenFOAM/OpenFOAM-v1812/src/OpenFOAM/lnInclude/typeInfo.H at line 158.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::IOerror::abort() at ??:?
#2  Foam::lduInterface const& Foam::refCast<Foam::lduInterface const, Foam::fvPatch const>(Foam::fvPatch const&, Foam::dictionary const&) at ??:?
#3  Foam::cyclicFvPatchField<Foam::Vector<double> >::cyclicFvPatchField(Foam::fvPatch const&, Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) at ??:?
#4  Foam::fvPatchField<Foam::Vector<double> >::adddictionaryConstructorToTable<Foam::cyclicFvPatchField<Foam::Vector<double> > >::New(Foam::fvPatch const&, Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) at ??:?
#5  Foam::fvPatchField<Foam::Vector<double> >::New(Foam::fvPatch const&, Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#6  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::Boundary::readField(Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::dictionary const&) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#7  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::readFields(Foam::dictionary const&) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#8  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::readFields() in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#9  Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh>::GeometricField(Foam::IOobject const&, Foam::fvMesh const&, bool) in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#10  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#11  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#12  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields
#13  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
#14  ? in ~/OpenFOAM/dyfluid-v1812/platforms/linux64GccDPInt32Opt/bin/funkySetFields

**Comment by CyrilleBonamy** [comment]
I don't know... I think it is related to funkySetFields and not sedfoam.
Maybe you can check the patches in the "boundary" file (in constant/polyMesh) and in 0/Ua (to be sure they are the same)

**Comment by ramap1219** [comment]
Hi, thanks much that's working, btw what version of OF you guys using?

**Comment by CyrilleBonamy** [comment]
The last ESI version if possible.

openfoam2012

**Comment by wbw-wb** [comment]
thanks much that's working,I will keep following you
